In [1]:
from IPython.display import display
import ipywidgets as widgets
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from elarb.policy import (
    optimal_policy, PolicyInput,
)
from elarb.models import (
    SolarPanel,
    Battery,
    GridConnection,
    Inverter,
)

In [2]:
panel = SolarPanel(m2=1.0, depreciation_per_hour=0.0)
print(panel)

SolarPanel(m2=1.0, depreciation_per_hour=0.0)


In [3]:
# DK grid
grid = GridConnection(throughput_kWh=10)
print(grid)

GridConnection(throughput_kWh=10)


In [4]:
# Deye SUN-12K-SG04LP3-EU
inverter = Inverter(depreciation_per_hour=0.0, throughput_kWh=10, conversion_loss_pct=0.0,)
print(inverter)

Inverter(depreciation_per_hour=0.0, throughput_kWh=10, conversion_loss_pct=0.0)


In [5]:
battery = Battery(depreciation_per_kWh=0.0, throughput_kWh=1.0, capacity_kWh=10, conversion_loss_pct=0.0,)
print(battery)

Battery(depreciation_per_kWh=0.0, throughput_kWh=1.0, capacity_kWh=10, conversion_loss_pct=0.0)


In [12]:
n = 2
spot_price      = np.array([0,1])
pv_kWh          = np.ones(n)
spot_demand_kWh = np.ones(n)*10
spot_supply_kWh = np.ones(n)*10

policy_input = PolicyInput(
    pv_kWh=pv_kWh,
    spot_price=spot_price,
    spot_demand_kWh=spot_demand_kWh,
    spot_supply_kWh=spot_supply_kWh,
    panel=panel,
    battery=battery,
    inverter=inverter,
    grid=grid,
    n_panels=0,
    n_batteries=1,
    n_inverters=1,
    initial_soc=0.0
)

res = optimal_policy(policy_input)

print(res.x1)
print(res.x2)
print(res.x3)
print(res.x4)
print(res.battery_soc_kWh.round(2))

[0.00000000e+00 1.29065187e-12]
[2.89687215e-12 0.00000000e+00]
[9.94289672e-13 1.00000000e+00]
[1.00000000e+00 5.60082673e-12]
[0. 1.]


In [7]:
# check soc as function of x3 x4
# check that static price -> no battery use
# check objective value

In [10]:
n = 4
spot_price = np.array([1,1,2,2])
pv_kWh     = np.array([1,1,1,1])

policy_input = PolicyInput(
    pv_kWh=pv_kWh,
    spot_price=spot_price,
    spot_demand_kWh=np.ones(n)*10,
    spot_supply_kWh=np.ones(n)*10,
    panel=panel,
    battery=battery,
    inverter=inverter,
    grid=grid,
    n_panels=1,
    n_batteries=0,
    n_inverters=1,
    initial_soc=0.0
)

res = optimal_policy(policy_input)

print(res.x1.round(2))
print(res.x2.round(2))
print(res.x3.round(2))
print(res.x4.round(2))
print(res.battery_soc_kWh.round(2))

[1. 1. 1. 1.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]


In [9]:
import cvxpy as cp
var = cp.Parameter(10)
var.value = np.arange(10)
var[:5].value

array([0, 1, 2, 3, 4])